services:

  ######################### insight-engine #########################
  insight_engine:
    image: insight_engine:latest
    build:
      context: ../
      dockerfile: ./applications/insight_engine/Dockerfile
    env_file:
      - ./insight_engine/docker-compose.env
    volumes:
      - ./insight_engine/src:/src
      - ./insight_engine/requirements:/requirements
      - /tmp/chroma:/chroma

  ######################### insight-crawler #########################
  insight_crawler:
    image: insight_crawler:latest
    build:
      context: ../
      dockerfile: ./applications/insight_crawler/Dockerfile
    env_file:
      - ./insight_crawler/docker-compose.env
    ports:
      - "8080:8080"
    volumes:
      - ./insight_crawler/src:/src
      - ./insight_crawler/requirements:/requirements
       - /tmp/chroma:/chroma
